jdk: openjdk11

services:
  - docker

script:
  - cd akash-demo
  - mvn clean verify
  - docker build -t akashdollar/akash-demo .
  - cd ..
  - cd akash-demo-app-angular
  - docker build -t akashdollar/akash-demo-app-angular .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push akashdollar/akash-demo;
    docker push akashdollar/akash-demo-app-angular;
    fi